name: Flight delays scrape

on:
  schedule:
    - cron: "*/5 * * * *"   #Run every 5 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libxml2-dev \
            libmagick++-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev \
            pandoc \
            git

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/Rlib
          key: ${{ runner.os }}-R-${{ hashFiles('**/scripts/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/Rlib
          echo 'R_LIBS_USER=~/Rlib' >> ~/.Renviron
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ~/.Rprofile
          Rscript -e 'install.packages("tidyverse", dependencies = TRUE, lib="~/Rlib")'
          Rscript -e 'install.packages(c("jsonlite", "remotes", "magick", "usethis"), dependencies = TRUE, lib="~/Rlib")'
          Rscript -e 'remotes::install_github("munichrocker/DatawRappr", lib="~/Rlib", auth_token=Sys.getenv("GITHUB_PAT"))'
          Rscript -e '.libPaths("~/Rlib"); if (!require("tidyverse", lib.loc = "~/Rlib")) stop("tidyverse did not install")'
          
      - name: Run scraper
        env:
          API_KEY: ${{ secrets.DW_API_KEY }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
        run: |
                . ~/.Renviron
                Rscript "flight-aware.R"
            
