name: Flight delays scrape

on:
  schedule:
    - cron: "*/15 * * * *"   #Run every 5 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest
            any::tidyverse
            any::dplyr
            any::jsonlite
      - name: Install DatawRappr package
        run: |
          Rscript -e "pak::pkg_install('munichrocker/DatawRappr')"

      - name: Run scraper
        env:
          API_KEY: ${{ secrets.DW_API_KEY }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
        run: Rscript flight-aware.R
